### ISSUE TITLE
Add "Lebensmittelwarnungen"-API to Results

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#115]
## Proposed changes
Add the outcome of the bavarian/German "Lebensmittelwarnungen" (Food warning) API ([documented by bund.dev](https://github.com/bundesAPI/lebensmittelwarnung-api)) to the results page if applicable. 

The following request via PHP requests() should work:
````php
$headers = array(
    'Authorization' => 'baystmuv-vi-1.0 os=ios, key=9d9e8972-ff15-4943-8fea-117b5a973c61',
    'Content-Type' => 'application/json'
);
$data = '{"food":{"rows": 10000}}';
````
Responses look something like this:
````json
"response":{
      "docs":[
         {
            "_type":".FoodWarning",
            "archived":false,
            "id":7199,
            "link":"https://www.lebensmittelwarnung.de/bvl-lmw-de/detail/lebensmittel/77462",
            "publishedDate":1645198768000,
            "title":"Oat King Haferriegel \"Milk & Honey\"",
            "warning":"Es kann nicht ausgeschlossen werden, dass in einzelnen Haferriegeln Salmonellen enthalten sind.",
            "affectedStates":[
               "Baden-Württemberg",
               "Bayern",
               "Berlin",
               "Hessen",
               "Niedersachsen",
               "Nordrhein-Westfalen",
               "Rheinland-Pfalz",
               "Sachsen",
               "Schleswig-Holstein"
            ],
            "product":{
               "_type":".FoodWarning$Food",
               "designation":"<div>\n  Oat King Haferriegel \"Milk &amp; Honey\"\n <br> \n</div>",
               "imageUrls":[
                  "https://www.lebensmittelwarnung.de/bvl-lmw-de/opensaga/attachment/05e5e2c6-ba35-46e4-9749-c779874c3714/Foto OatKing.JPG"
               ],
               "manufacturer":"LSP Sporternährung GmbH Römerstr. 45-51 53111 Bonn"
            }
         }
      ],
      "numFound":278
}
````

I'd suggest we are checking parts of the product names against `docs→title` and then inform the user that there may be a food warning (Without any specific information). 

## Tasks
- [x] Create API request file
- [x] Set up cronjob for local hosting
- [ ] Check with the product in `script.php` and return warning as `$Lebensmittelwarnung`
- [ ] Push to production
- [ ] Integrate into API (optional)

**Comment by philipbrembeck** [comment]
This won't work until they include EANs in their warnings.

Code: 
````php
<?php
$warnings = file_get_contents('warnings.json');
$warn = json_decode($warnings);
$name = "Omegalul";
$Lebesmittelwarnungen = array();
foreach ($warn->response->docs as $key => $value) {
	$Lebesmittelwarnungen[] = $value->title;
	if (strpos($value->title, $name) !== false) { $Lebesmittelwarnungen[] = $value->title; }
}
print_r($Lebesmittelwarnungen);
?>
````
Will always be true, because something is always included.

**Comment by philipbrembeck** [comment]
https://vegancheck.me/includes/lebensmittelwarnung
