### ISSUE TITLE
Simplify Localization with php-i18n and convert to json

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#117]
## Proposed changes

Add [`philipp15b/php-i18n`](https://github.com/philipp15b/php-i18n) `i18n.class.php` via composer:
````bash
$ composer require philipp15b/php-i18n
```` 
and convert current localizations to `JSON`.

## Tasks
- [x] Require class
- [x] Change `localization` folder to `l10n`
- [x] Convert php-arrays to json
- [x] Implement in all applicable pages:
   - [x] `script.php`
   - [x] `impressum.php`
   - [x] `privacy-policy.php`
   - [x] `offline.php`
   - [x] `main.php` 
 - [ ] Debate restructuring language-code named folders
 - [x] Edit README!
 - [x] Push & publish
