### ISSUE TITLE
[Feature request] Integrate VeganCheck Grades

### ISSUE THREAD

**Issue by gitgauner** [frontendnetwork/veganify#123]
#### Introduction
As discussed on discord I'd love to see VeganCheck integrating it's own grade based system to rate some **vegan** products (Food, non-food, Beauty).

#### Grade system 

Grades could be calculated something like this:
- Grade A+
  Handpicked: Sustainable (e.g. soy from europe), not made with any palm-oil, carbon-neutral, no animal cruelty, company does not produce any other products which are made from animals, company is not associated with any other harmful actions (e.g. Nestlé), good nutritional value if applicable (foods), proven health-claims if applicable (food and beauty), proven effect if applicable (beauty), Independent laboratory analysis where relevant, price is relatively fair, only necessary packaging, produced with renewable energies

- Grade A
  Everything from Grade A applies, except the fair price, the independent laboratory analysis and production with renewable energies

- Grade B
  Not made with palm-oil, no animal-cruelty, company is not associated with any other harmful actions, good nutritional value if applicable (foods), proven health-claims if applicable (food and beauty), proven effect if applicable (beauty)

- Grade C
  Made with at least **sustainable** palm-oil (we would have to declare this), good nutritional value if applicable (foods), proven health-claims if applicable (food and beauty), proven effect if applicable (beauty)

- Grade D
  proven health-claims if applicable (food and beauty), proven effect if applicable (beauty)

- Grade Not eligible
  All other products are not eligible for evaluation and are not recommended for purchase.

- Not rated yet
  For every product we still have to rate.

#### Mockup
<img width="570" alt="mockup_1603_final" src="https://user-images.githubusercontent.com/87610380/158685563-7b793828-caf9-404a-a08f-3934ab0df138.png">

----
This would replace #3 

### Tasks
- [x] Collect data with volunteers 
  - [x] Build data collecting platform
  - [x] Find contributors
  - [x] Reach ~100 entries
  - [ ] Reach ~300 entries
- [x] Validate data by sampling
- [ ] Publish results as a repo & integrate as submodule
- [x] Integrate data into VeganCheck.me
  - [x] Create an API

**Comment by philipbrembeck** [comment]
As I've already said, I love this idea but we will need volunteers to rate products. I'll ask a few vegan/veggie friends.

Here's a ruff chart of how the data collection should work in the first place:
![drawio](https://user-images.githubusercontent.com/4144601/158889400-ee571af4-5eb0-4c0b-90a7-8e7fa044cd80.png)

I'll work on the survey-PWA as soon as I have time for it.
I'll integrate the first results then asap.

**Comment by philipbrembeck** [comment]
Grades are now being collected on https://grades.vegancheck.me.
If anyone needs a login, please send me an email.

**Comment by philipbrembeck** [comment]
**Update**: We're now at around 100 entries and I'm now going to check some of the collected data by sampling.
This could take some time, after that is been done, I'll wait for another like 200 products to be added, check them again and then publish the first results as a repo and add it as a submodule. 
Integration will then be the main focus but I'll also think of the possibility to open the rating page for everyone.

**Comment by philipbrembeck** [comment]
**Update:** Through an error on my side, most of the rated products were deleted on accident. Because of this, I will design a new way to save the results. This will delay integration into VeganCheck and we'll also need more raters.

**Comment by philipbrembeck** [comment]
The Grade-Promotion page is now available at https://grade.vegancheck.me – A rating for a product can be requested there too. 
Additionally, the already existing Grades are integrated into the new Node.js API v0. 

The API still has to be integrated into VeganCheck.me, since the site is using `script.php` for this at the moment.
