### ISSUE TITLE
VeganCheck.me API

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#85]
VeganCheck.me now combines several different APIs that together have a stable data base for various products with EAN or UPC codes.  
For the release of VeganCheck v2.0.x, we're planning a read-only JSON API, where anyone can use this data to check products for certain things, such as palm-oil content, name, etc.

## Roadmap 
- [x] Create basic API
- [x] Check for rate limitations
- [x] Integrate OFF/OBF
- [x] Integrate is-vegan
- [x] Integrate Brocade.io
- [x] Integrate OEDB 
- [x] Alpha testing
   - [x] Form of Authorization
   - [x] Format of response
   - [x] Max. limitations
   - [x] Denial of Service Protection
- [x] Public beta testing
- [x] Release

**Comment by philipbrembeck** [comment]
So, a request like:
````bash
curl -X GET \
  'https://vegancheck.me/api/v0/product?product=4251105511243' \
  --header 'AUTH-KEY: alpha'
````

generates a response like:
````json
{
  "code": "OK",
  "status": "200",
  "message": "Success",
  "data": {
    "name": "No Whey vegan chocolate peanut",
    "is_vegan": "true",
    "is_vegetarian": "true",
    "contains_palmoil": "n/a",
    "nutriscore": "B",
    "not_tested_on_animals": "n/a",
    "data_source": {
      "database": "OpenFoodFacts",
      "uri": "https://world.openfoodfacts.org/product/4251105511243"
    }
  }
}
````

Note that the`AUTH-KEY` "alpha" is currently limited to 5 requests/day, it's for testing purposes only.

**Comment by philipbrembeck** [comment]
Can also be done through a POST request:
````bash
curl -X POST \
  'https://vegancheck.me/api/v0/product' \
  --header 'AUTH-KEY: alpha' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'ean=4337256282826'
````

Responses are quite slow right now, may have to work on this.

**Comment by philipbrembeck** [comment]
The first alpha is now live. Closed.
